//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gentry
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using System.Web.Mvc;
    
    public partial class tbl_Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Products()
        {
            this.tbl_Cart = new HashSet<tbl_Cart>();
        }

        public int ProductId { get; set; }

        [Required(ErrorMessage = "Product name is required.")]
        [DisplayName("Product Name")]
        public string ProductName { get; set; }

        [Required(ErrorMessage = "Product description is required.")]
        [DisplayName("Product Description")]
        public string ProductDescription { get; set; }
        public string Unit { get; set; }
        [DisplayName("Sale Rate")]
        public Nullable<decimal> SaleRate { get; set; }
        [DisplayName("Purchase Rate")]
        public Nullable<decimal> PurchaseRate { get; set; }
        public Nullable<int> CatId { get; set; }

        public SelectList categoryList { get; set; }
        public string ImagePath { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Cart> tbl_Cart { get; set; }
        public virtual tbl_Categories tbl_Categories { get; set; }
    }
}
