//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int OrderId { get; set; }
        public int ProdId { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> ProductRate { get; set; }
    
        public virtual OrderMaster OrderMaster { get; set; }
        public virtual tblProduct tblProduct { get; set; }

    }
}
